name: 'Vifyx'
services:
  frontend:
    build:
      context: .
    ports:
      - '3000:3000'
    restart: always
  nginx:
    build:
      context: ./.nginx/
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.nginx/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - frontend
